-- moderation-service schema, generated from the EF Core migrations of moderation-service 0.2.0
-- with `dotnet ef migrations script --idempotent`. Safe to run more than once.
-- Do not edit this copy; see README.md.

CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    migration_id character varying(150) NOT NULL,
    product_version character varying(32) NOT NULL,
    CONSTRAINT pk___ef_migrations_history PRIMARY KEY (migration_id)
);

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260923141448_InitialCreate') THEN
    CREATE TABLE decision (
        id uuid NOT NULL,
        session_id uuid NOT NULL,
        applicant_id uuid NOT NULL,
        credential_id uuid NOT NULL,
        moderator_id uuid NOT NULL,
        action character varying(16) NOT NULL,
        created_at timestamp with time zone NOT NULL,
        updated_at timestamp with time zone,
        voided_at timestamp with time zone,
        CONSTRAINT pk_decision PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260923141448_InitialCreate') THEN
    CREATE TABLE outbox_message (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        event_id uuid NOT NULL,
        event_type character varying(64) NOT NULL,
        payload json NOT NULL,
        occurred_at timestamp with time zone NOT NULL,
        published_at timestamp with time zone,
        attempts integer NOT NULL,
        last_error character varying(1024),
        CONSTRAINT pk_outbox_message PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260923141448_InitialCreate') THEN
    CREATE TABLE verdict (
        decision_id uuid NOT NULL,
        correct boolean NOT NULL,
        expected_action character varying(16) NOT NULL,
        xp_awarded integer NOT NULL,
        ruleset_id uuid NOT NULL,
        ruleset_version integer NOT NULL,
        evaluated_at timestamp with time zone NOT NULL,
        CONSTRAINT pk_verdict PRIMARY KEY (decision_id),
        CONSTRAINT fk_verdict_decision_decision_id FOREIGN KEY (decision_id) REFERENCES decision (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260923141448_InitialCreate') THEN
    CREATE TABLE violation (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        decision_id uuid NOT NULL,
        rule_code character varying(64) NOT NULL,
        detail character varying(512) NOT NULL,
        CONSTRAINT pk_violation PRIMARY KEY (id),
        CONSTRAINT fk_violation_verdict_decision_id FOREIGN KEY (decision_id) REFERENCES verdict (decision_id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260923141448_InitialCreate') THEN
    CREATE INDEX ix_decision_session_id ON decision (session_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260923141448_InitialCreate') THEN
    CREATE UNIQUE INDEX ux_decision_session_applicant_active ON decision (session_id, applicant_id) WHERE voided_at IS NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260923141448_InitialCreate') THEN
    CREATE UNIQUE INDEX ix_outbox_message_event_id ON outbox_message (event_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260923141448_InitialCreate') THEN
    CREATE INDEX ix_outbox_message_published_at ON outbox_message (published_at);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260923141448_InitialCreate') THEN
    CREATE INDEX ix_violation_decision_id ON violation (decision_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260923141448_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
    VALUES ('20260923141448_InitialCreate', '8.0.31');
    END IF;
END $EF$;
COMMIT;
